site_name: Umbra Docs
repo_url: "https://github.com/ayvacs/umbra-docs"
repo_name: ayvacs/umbra
copyright: Copyright &copy; 2021 AYVACS on behalf of Umbra Software
theme:
  name: material
  custom_dir: overrides
  logo: assets/icon.png
  favicon: assets/favicon.ico
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: slate
    primary: black
    accent: indigo
  features:
    - navigation.tabs
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/icon.png

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

extra:
  social:
    - icon: fontawesome/brands/git-alt
      link: https://github.com/ayvacs
    - icon: fontawesome/brands/github
      link: https://github.com/ayvacs/umbra

nav:
  - Home: index.md
  - API:
    - Classes: api/classes.md