site_name: Umbra Docs
repo_url: "https://github.com/ayvacs/umbra-docs"
repo_name: ayvacs/umbra-docs
copyright: Copyright &copy; 2022 AYVACS on behalf of Umbra Software
theme:
  name: material
  custom_dir: overrides
  logo: assets/icon.png
  favicon: assets/favicon.ico
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: slate
    primary: black
    accent: indigo
  features:
    - navigation.tabs
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/icon.png

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

extra:
  social:
    - icon: fontawesome/brands/git-alt
      link: https://github.com/ayvacs
    - icon: fontawesome/brands/github
      link: https://github.com/ayvacs/umbra

nav:
  - Home:
    - Welcome: index.md
    - Getting started: scripting/getting-started.md
    - Managing your Umbra account: scripting/my-account.md
    - Umbra DevKit:
      - Create an account: devkit/create-an-account.md
      - Create and publish scripts: devkit/create-scripts.md
      - Accept transactions: devkit/accept-transactions.md
    - Umbra WebAPI:
      - Home: web-api/index.md
    - Copyright &copy; 2022 AYVACS on behalf of Umbra Software: legal/index.md
  - Engine Literals: engine/index.md
  - Classes: 
    - HttpRequest: classes/http-request.md
    - HttpResponse: classes/http-response.md
    - Identity: classes/identity.md
    - Release: classes/release.md

    - Codesign: classes/codesign.md
  - Enums:
    - Subscription: enums/subscription.md
    - SubType: enums/subtype.md
  - Libraries:
    - fe: lib/fe.md
    - http: lib/http.md
    - net: lib/net.md
    - Umbra: lib/umbra.md
  - 45: ai/index.md
  - Feature Board: https://ave.is-a.dev/umbra/notion